baseURL: "https://www.dorislt.com" 
title: Doris Lanzkron-Tamarazo
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Projects
          url: projects/
          weight: 1
        - name: Exhibits
          url: exhibits/
          weight: 4 


params:
    description: "This website hosts Doris Lanzkron-Tamarazo's Professional Portfolio."
    author: Doris Lanzkron-Tamarazo
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["resume","papers","projects","exhibits"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Doris Lanzkron-Tamarazo
          subtitle: "I am a graduate student of public history at Wayne State University, specializing in Detroit history."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/
            - name: Papers
              url: papers/
            - name: Exhibits
              url: exhibits/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:dorislanzkrontamarazo@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=mbayBEgAAAAJ
        - name: LinkedIn
          url: https://www.linkedin.com/in/doris-lanzkron-tamarazo-61a413217/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Doris Lanzkron-Tamarazo"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2